### ISSUE TITLE
Babel Config Not Working Properly

### ISSUE THREAD

**Issue by kcgunn** [leftstick/generator-mobx-react#1]
I'm running this project on a MAC OS box...getting compile errors on ES2015 features, mainly spread operator and arrow functions. Getting unexpected token on these, but they are part of the es2015 feature set. Possibility that Babel is not setup correctly?

**Comment by leftstick** [comment]
Can you provide more error info? I think there is something wrong with your env.

**Comment by yuchunbo** [comment]
I think you might put the ES2015 features in *.jsx files , you can resolve this issue by write the ES2015 syntax in *.js
